apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EVXdNVEUzTlRJMU9Wb1hEVE16TURReU9ERTNOVEkxT1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS3o1CmFka25MUjBDdmRxZXlrUGk1d0N3YnN6blZCaWFiSFlBUjdUNmt3VzByVFU3TmpnbHdBOS96Q1hFaVRTaCtaMGUKMXFmMDN1UUw0THorVGsyVnphcktEbGZPRi9KODV4Q01INzhxVm81eHVhaUYxTm9HeFlKaktTeGVnam15Z2gwdgp4c1pieHlDUXR6V2xIeU9ZcFpqeWtML1lhclE0enhhRmpYZkE1RFdoV3RVd3VwRlArT0xOMGNLS0U0K2d4RTMwCjBXL0M3dGJUVWppTTFCR1JkYnhDb2V5dUpSMVBVNjJYY2YzWStSUWFOM01EMUZTTVR1bkxodXVKblV4SEU2aEEKVkNTc09kZklIRzJiVGdiTkZ2dnRVZlhEYWE5VlVnV0JVS3ZxN0l6UnNhNW5MaG9ycitnaDlZTFVYVzBvV1hpbgpWWWlBUXlIeWY4Q25CQWRVMHA4Q0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZHQ0J6dGVBdFhBTDhrOExCcFNjZk15TW1oZ0NNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBR3BCcDdBNGhVcGV3UGUwUU1oaAp6UWZ6UG5xSXlidGlwcmpabE9TWWE3a25lTzlqeWpkN051dE9mY2xnZU9mQk52eWRmWUZ4VVBOeUMvZGNLQ0d5CjY3eVg0ejhDUEFLam9iR2ZOS2IrMmR1Y2NaQy8wTzVKTkNINUFGV0pEaEl3c0UvMGh0VVpYZm90eUNCZVg3cEgKcTZUQkdUYU1nclo3a0krdHBTMytmLzUxVVRwdjMwbFdMT3FrZWU1eXl1UU9pYVptR1RjWTFrWkltQnlxVnlXegpyNUw0aFlla0FkdTR6bU1Bd0pBOEk3NGlkM0pWSmtjKzhUZ0s5bXZyKzVaN0prRzRRemFmWFNVNU53OE1VUHArCjc0SEhUQVR6dzZBaE0ra25abmQxWTdzak5lVzBEQ3ZHbHY5Y2hzcFdpVUEwajVudUlpL0NBdTVvSHpYNGVmUmoKVG9RPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://85B9B18149A91C3E4C1918785C1AB626.gr7.eu-central-1.eks.amazonaws.com
  name: demo-cluster.eu-central-1.eksctl.io
contexts:
- context:
    cluster: demo-cluster.eu-central-1.eksctl.io
    user: iam-root-account@demo-cluster.eu-central-1.eksctl.io
  name: iam-root-account@demo-cluster.eu-central-1.eksctl.io
current-context: iam-root-account@demo-cluster.eu-central-1.eksctl.io
kind: Config
preferences: {}
users:
- name: iam-root-account@demo-cluster.eu-central-1.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - eks
      - get-token
      - --cluster-name
      - demo-cluster
      - --region
      - eu-central-1
      command: aws
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      provideClusterInfo: false
